### ISSUE TITLE
Geraldine's webpage

### ISSUE THREAD

**Issue by LouisaEncel** [LouisaEncel/IPT2_GroupRepository#11]
@GeraRivera 
Make sure na matapos mo din yung webpage mo for the "IT Specialists" webpage.
Make sure to edit the following:
1. Name
2. Your Photo
3. "About Me"
4. Your viewable resume (sa button)
5. "Skills"
6. "Services"

**Comment by GeraRivera** [comment]
done na ako sa webpage kooo
![image](https://github.com/LouisaEncel/IPT2_GroupRepository/assets/159447276/9f77e046-6a1e-4fd0-8c31-dc9f32e5fec9)
