### ISSUE TITLE
Joanne's webpage

### ISSUE THREAD

**Issue by LouisaEncel** [LouisaEncel/IPT2_GroupRepository#12]
@JoannCarla 
Make sure na matapos mo din yung webpage mo for the "IT Specialists" webpage.
Make sure to do the following:
1. Name
2. Your Photo
3. "About Me"
4. Your viewable resume (sa button)
5. "Skills"
6. "Services"

**Comment by JoannCarla** [comment]
Done na rin ako sa webpage ko. 
![image](https://github.com/LouisaEncel/IPT2_GroupRepository/assets/159448360/5d885fba-f57d-43ab-912c-320967f5d6ad)
