### ISSUE TITLE
Grace Anne's webpage

### ISSUE THREAD

**Issue by LouisaEncel** [LouisaEncel/IPT2_GroupRepository#9]
@GraceAnneBondoc 
Make sure na matapos mo yung webpage mo for the "IT Specialists" webpage.
Make sure to edit the following:
1. Name
2. Your Photo
3. "About Me"
4. Your viewable resume (sa button)
5. "Skills"
6. "Services"

**Comment by GraceAnneBondoc** [comment]
Ocakes na yung saakin, done na.
![image](https://github.com/LouisaEncel/IPT2_GroupRepository/assets/159441390/ad3503bd-ac08-4348-9850-375774691d2e)
